-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cidade_carne
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cidade_carne
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cidade_carne` DEFAULT CHARACTER SET utf8 ;
USE `db_cidade_carne` ;

-- -----------------------------------------------------
-- Table `db_cidade_carne`.`tb_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cidade_carne`.`tb_categorias` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- Seleção da tabela tb_categorias
SELECT * FROM tb_categorias;

-- Inserindo dados na tabela
INSERT INTO tb_categorias (marca, tipo)
VALUE ("FriBoi", "Platinum");

INSERT INTO tb_categorias (marca, tipo)
VALUE ("FriBoi", "Gold");

INSERT INTO tb_categorias (marca, tipo)
VALUE ("FriBoi", "Prata");

INSERT INTO tb_categorias (marca, tipo)
VALUE ("FriBoi", "Bronze");

INSERT INTO tb_categorias (marca, tipo)
VALUE ("FriBoi", "Padrão");

-- -----------------------------------------------------
-- Table `db_cidade_carne`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cidade_carne`.`tb_produtos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `corte` VARCHAR(255) NOT NULL,
  `preco` DECIMAL(6,2) NOT NULL,
  `porte` VARCHAR(255) NOT NULL,
  `tb_categorias_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_produtos_tb_categorias_idx` (`tb_categorias_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produtos_tb_categorias`
    FOREIGN KEY (`tb_categorias_id`)
    REFERENCES `db_cidade_carne`.`tb_categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Seleção da tabela tb_categorias
SELECT * FROM tb_produtos;

-- Inserindo os dados na tabela
INSERT INTO tb_produtos (nome, corte, preco, porte, tb_categorias_id)
VALUE ("Boi", "Picanha", 130.25, "Gramde", 1);

INSERT INTO tb_produtos (nome, corte, preco, porte, tb_categorias_id)
VALUE ("Boi", "Filé minhong", 195.75, "Gramde", 1);

INSERT INTO tb_produtos (nome, corte, preco, porte, tb_categorias_id)
VALUE ("Boi", "Fraudinha", 48.98, "medium", 3);

INSERT INTO tb_produtos (nome, corte, preco, porte, tb_categorias_id)
VALUE ("Boi", "Ponta de Alcatra", 38.20, "pequeno", 5);

INSERT INTO tb_produtos (nome, corte, preco, porte, tb_categorias_id)
VALUE ("Boi", "Cochão mole", 34.98, "Gramde", 4);

INSERT INTO tb_produtos (nome, corte, preco, porte, tb_categorias_id)
VALUE ("Boi", "Figado", 25.30, "Gramde", 2);

INSERT INTO tb_produtos (nome, corte, preco, porte, tb_categorias_id)
VALUE ("Boi", "Alcatra", 42.56, "medium", 2);

INSERT INTO tb_produtos (nome, corte, preco, porte, tb_categorias_id)
VALUE ("Boi", "Picadão", 31.45, "pequeno", 5);

-- Fazendo select das tabelas
SELECT * FROM tb_produtos WHERE preco > 50;

SELECT * FROM tb_produtos WHERE preco BETWEEN 50 and 150;

SELECT * FROM tb_produtos WHERE corte LIKE "%c%";

SELECT * FROM tb_produtos INNER JOIN tb_categorias
ON tb_produtos.tb_categorias_id = tb_categorias.id;

SELECT * FROM tb_produtos INNER JOIN tb_categorias
ON tb_produtos.tb_categorias_id = tb_categorias.id
WHERE tb_categorias.tipo = "Gold";

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;